#!/bin/python
"""
This software was AI generated by Claude sonnet 4.5
Use it at your own risk. The authors are not responsible for any issues or damage that may result.
"""
from flask import Flask, request, Response, stream_with_context
import requests
import json

app = Flask(__name__)

@app.route('/')
def ui():
    return '''
    <!DOCTYPE html>
    <html>
    <head>
        <title>Ollama Chat</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/marked/9.1.6/marked.min.js"></script>
        <style>
        .message ul, .message ol {
            margin: 10px 0;
            padding-left: 20px;
        }
        .message li {
            margin: 5px 0;
        }
        .message strong {
            font-weight: 600;
        }
        .message code {
            background: rgba(0,0,0,0.1);
            padding: 2px 6px;
            border-radius: 3px;
            font-family: monospace;
        }
        body.night .message code {
            background: rgba(255,255,255,0.1);
        }
        .message pre {
            background: rgba(0,0,0,0.1);
            padding: 10px;
            border-radius: 6px;
            overflow-x: auto;
            margin: 10px 0;
        }
        body.night .message pre {
            background: rgba(255,255,255,0.1);
        }
        .message pre code {
            background: none;
            padding: 0;
        }
        * { box-sizing: border-box; margin: 0; padding: 0; }
        html, body {
            height: 100%;
            overflow: hidden;
        }
        body {
            font-family: -apple-system, BlinkMacSystemFont, sans-serif;
            background: white;
            color: #333;
            transition: all 0.3s;
            display: flex;
            flex-direction: column;
        }
        body.night {
            background: #1a1a1a;
            color: #e0e0e0;
        }
        .container {
            display: flex;
            flex-direction: column;
            height: 100%;
            padding: 20px;
            padding-bottom: 0;
        }
        .header {
            margin-bottom: 15px;
        }
        h1 {
            font-size: 24px;
        }
        .model-row {
            display: flex;
            gap: 10px;
            margin-bottom: 10px;
        }
        .button-row {
            display: flex;
            gap: 10px;
            margin-bottom: 15px;
        }
        .button-row button,
        .button-row .toggle-mode {
            flex: 1;
        }
        select, input, button {
            padding: 12px;
            border: 1px solid #ddd;
            border-radius: 6px;
            font-size: 16px;
            background: white;
            transition: all 0.3s;
        }
        body.night select,
        body.night input,
        body.night button {
            background: #2d2d2d;
            border-color: #444;
            color: #e0e0e0;
        }
        select { flex: 1; min-width: 120px; }
        #chat {
            flex: 1;
            overflow-y: auto;
            margin-bottom: 15px;
            padding: 10px;
            border: 1px solid #eee;
            border-radius: 6px;
            background: #fafafa;
            transition: all 0.3s;
            -webkit-overflow-scrolling: touch;
        }
        body.night #chat {
            background: #2d2d2d;
            border-color: #444;
        }
        .message {
            background: #3a3a3a;
            margin: 10px 0;
            padding: 12px;
            border-radius: 8px;
            max-width: 85%;
            word-wrap: break-word;
            line-height: 1.4;
            position: relative;
        }
        .user {
            background: #94702e;
            color: #333;
            margin-left: auto;
            white-space: pre-wrap;
        }
        .bot {
            background: #eae8e5;
            color: #333;
            cursor: pointer;
            padding-left: 40px;
        }
        body.night .bot {
            background: #3a3a3a;
            color: #e0e0e0;
        }
        .bot::before {
            content: '📋';
            position: absolute;
            right: 12px;
            top: 50%;
            font-size: 18px;
            opacity: 0.4;
            transition: opacity 0.2s;
        }
        .bot:hover::before {
            opacity: 1;
        }
        .bot.copied::after {
            content: 'Copied!';
            position: absolute;
            left: 12px;
            top: 50%;
            background: #28a745;
            color: white;
            padding: 4px 8px;
            border-radius: 4px;
            font-size: 12px;
            animation: fadeOut 2s forwards;
        }
        @keyframes fadeOut {
            0% { opacity: 1; }
            70% { opacity: 1; }
            100% { opacity: 0; }
        }
        .input-area {
            display: flex;
            gap: 10px;
            align-items: center;
            position: sticky;
            bottom: 0;
            background: #3a3a3a;
            padding: 15px 0;
            padding-bottom: 20px;
        }
        #input {
            flex: 1;
            min-height: 45px;
            max-height: 150px;
            resize: vertical;
            font-family: inherit;
            line-height: 1.4;
            padding-right: 50px;
            padding-left: 5px;
            background: #8f8f8f;
        }
        #sendBtn {
            position: absolute;
            right: 10px;
            bottom: 10px;
            background: #007AFF;
            color: white;
            border: none;
            cursor: pointer;
            font-weight: 600;
            width: 40px;
            height: 40px;
            border-radius: 50%;
            display: flex;
            align-items: center;
            justify-content: center;
            font-size: 20px;
            padding: 0;
        }
        #sendBtn:hover { opacity: 0.9; }
        #sendBtn:disabled {
            background: #ccc;
            cursor: not-allowed;
        }
        body.night #sendBtn:disabled {
            background: #555;
        }
        .toggle-mode {
            background: transparent;
            border: 1px solid #ddd;
            color: #333;
            padding: 12px;
            font-size: 16px;
            cursor: pointer;
        }
        body.night .toggle-mode {
            border-color: #666;
            color: #e0e0e0;
        }
        .streaming {
            /* animation: pulse 1.5s ease-in-out infinite; */
        }
        @keyframes pulse {
            0%, 100% { opacity: 1; }
            50% { opacity: 0.5; }
        }
        @media (max-width: 600px) {
            .container {
                padding: 10px;
                padding-bottom: 0;
            }
            h1 {
                font-size: 20px;
            }
            .message { 
                max-width: 95%; 
                font-size: 15px;
                padding: 10px;
            }
            .model-row { 
                flex-direction: column; 
            }
            select, button { 
                width: 100%; 
                font-size: 16px;
                padding: 12px;
            }
            #input {
                font-size: 16px;
            }
            #sendBtn {
                width: 45px;
                height: 45px;
                font-size: 22px;
            }
        }
        
        /* Fix for iOS Safari viewport */
        @supports (-webkit-touch-callout: none) {
            body {
                height: -webkit-fill-available;
            }
        }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h1>Ollama Chat</h1>
            </div>
            
            <div class="model-row">
                <select id="modelSelect">
                    <option value="llama2">Llama 2</option>
                </select>
            </div>
            
            <div class="button-row">
                <button class="toggle-mode" onclick="toggleNightMode()">🌙</button>
                <button onclick="loadModels()">Refresh Models</button>
                <button onclick="clearChat()">Clear Chat</button>
                <button id="stopBtn" onclick="stopGeneration()" style="display: none; background: #ff3b30; color: white;">Stop</button>
            </div>
            
            <div id="chat"></div>
            
            <div class="input-area">
                <textarea id="input" placeholder="Type your message..."></textarea>
                <button id="sendBtn" onclick="sendMessage()">➤</button>
            </div>
        </div>
        
        <script>
            const chat = document.getElementById('chat');
            const input = document.getElementById('input');
            const modelSelect = document.getElementById('modelSelect');
            const sendBtn = document.getElementById('sendBtn');
            let currentBotMessage = null;
            let abortController = null;
            let conversationHistory = [];
            
            function stopGeneration() {
                if (abortController) {
                    abortController.abort();
                    abortController = null;
                    finalizeBotMessage();
                    sendBtn.disabled = false;
                    document.getElementById('stopBtn').style.display = 'none';
                    input.focus();
                }
            }
            
            function toggleNightMode() {
                document.body.classList.toggle('night');
                localStorage.setItem('nightMode', document.body.classList.contains('night'));
            }
            
            function clearChat() {
                conversationHistory = [];
                chat.innerHTML = '';
                input.focus();
            }
            
            function copyToClipboard(text, element) {
                navigator.clipboard.writeText(text).then(() => {
                    element.classList.add('copied');
                    setTimeout(() => {
                        element.classList.remove('copied');
                    }, 2000);
                }).catch(err => {
                    console.error('Failed to copy:', err);
                });
            }
            
            function addMessage(text, isUser) {
                const msg = document.createElement('div');
                msg.className = `message ${isUser ? 'user' : 'bot'}`;
                msg.textContent = text;
                
                if (!isUser) {
                    msg.onclick = function() {
                        copyToClipboard(text, msg);
                    };
                }
                
                chat.appendChild(msg);
                chat.scrollTop = chat.scrollHeight;
                return msg;
            }
            
            function appendToBotMessage(text) {
                if (currentBotMessage) {
                    currentBotMessage.textContent += text;
                }
            }
            
            function createBotMessage() {
                const msg = document.createElement('div');
                msg.className = 'message bot streaming';
                msg.textContent = '';
                chat.appendChild(msg);
                chat.scrollTop = chat.scrollHeight;
                return msg;
            }
            
            function finalizeBotMessage() {
                if (currentBotMessage) {
                    currentBotMessage.classList.remove('streaming');
                    const rawText = currentBotMessage.textContent;
                    currentBotMessage.innerHTML = marked.parse(rawText);
                    
                    // Store raw text for copying
                    currentBotMessage.dataset.rawText = rawText;
                    currentBotMessage.onclick = function() {
                        copyToClipboard(rawText, currentBotMessage);
                    };
                    
                    // Add to conversation history
                    conversationHistory.push({
                        role: 'assistant',
                        content: rawText
                    });
                    
                    currentBotMessage = null;
                }
            }
            
            async function loadModels() {
                try {
                    const response = await fetch('/models');
                    const data = await response.json();
                    if (data.models) {
                        modelSelect.innerHTML = '';
                        data.models.forEach(model => {
                            const option = document.createElement('option');
                            option.value = model.name;
                            option.textContent = model.name;
                            modelSelect.appendChild(option);
                        });
                    }
                } catch (error) {
                    console.error('Failed to load models:', error);
                }
            }
            
            async function sendMessage() {
                const message = input.value.trim();
                const model = modelSelect.value;
                if (!message) return;
                
                input.value = '';
                sendBtn.disabled = true;
                document.getElementById('stopBtn').style.display = 'inline-block';
                addMessage(message, true);
                
                // Add user message to conversation history
                conversationHistory.push({
                    role: 'user',
                    content: message
                });
                
                currentBotMessage = createBotMessage();
                abortController = new AbortController();
                
                try {
                    const response = await fetch('/chat', {
                        method: 'POST',
                        headers: { 'Content-Type': 'application/json' },
                        body: JSON.stringify({
                            model: model,
                            messages: conversationHistory
                        }),
                        signal: abortController.signal
                    });
                    
                    if (!response.ok) {
                        throw new Error('Network response was not ok');
                    }
                    
                    const reader = response.body.getReader();
                    const decoder = new TextDecoder();
                    
                    while (true) {
                        const { done, value } = await reader.read();
                        if (done) break;
                        
                        const text = decoder.decode(value, { stream: true });
                        const lines = text.split('\\n');
                        
                        for (const line of lines) {
                            const trimmed = line.trim();
                            if (trimmed) {
                                try {
                                    const data = JSON.parse(trimmed);
                                    if (data.message && data.message.content) {
                                        appendToBotMessage(data.message.content);
                                    }
                                } catch (e) {
                                    // Skip invalid JSON
                                }
                            }
                        }
                    }
                    
                    finalizeBotMessage();
                } catch (error) {
                    console.error('Error:', error);
                    finalizeBotMessage();
                    if (error.name === 'AbortError') {
                        appendToBotMessage(' [Stopped by user]');
                        finalizeBotMessage();
                    } else if (currentBotMessage && !currentBotMessage.textContent) {
                        currentBotMessage.remove();
                        addMessage('Error: Could not connect to server', false);
                    }
                } finally {
                    sendBtn.disabled = false;
                    document.getElementById('stopBtn').style.display = 'none';
                    abortController = null;
                    input.focus();
                }
            }
            
            input.addEventListener('keydown', (e) => {
                // Enter key no longer sends message, just creates new line
                // Only send on button click
            });
            
            if (localStorage.getItem('nightMode') === 'true') {
                document.body.classList.add('night');
            }
            
            // Prevent zoom on iOS when focusing inputs
            const viewport = document.querySelector('meta[name=viewport]');
            viewport.setAttribute('content', 'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no');
            
            // Handle virtual keyboard on mobile
            if ('visualViewport' in window) {
                const viewport = window.visualViewport;
                const handleResize = () => {
                    const container = document.querySelector('.container');
                    container.style.height = `${viewport.height}px`;
                };
                viewport.addEventListener('resize', handleResize);
                viewport.addEventListener('scroll', handleResize);
            }
            
            loadModels();
            input.focus();
        </script>
    </body>
    </html>
    '''

@app.route('/chat', methods=['POST'])
def chat():
    data = request.json
    
    def generate():
        with requests.post(
            'http://localhost:11434/api/chat',
            json={
                'model': data.get('model', 'llama2'),
                'messages': data.get('messages', []),
                'stream': True
            },
            stream=True
        ) as response:
            for chunk in response.iter_content(chunk_size=None):
                if chunk:
                    yield chunk
    
    return Response(stream_with_context(generate()), content_type='application/x-ndjson')

@app.route('/models')
def models():
    try:
        response = requests.get('http://localhost:11434/api/tags', timeout=5)
        return response.json()
    except Exception as e:
        return {'error': str(e), 'models': []}, 500

if __name__ == '__main__':
    app.run(port=5000, debug=False, threaded=True)
